#! /usr/bin/python
#  -*- Python -*-

#
# A tempory utility program to fix problems in the CVS repository.
# This wouldn't be needed if we had shell access to the CVS server.
#
# When this program is added to the loginfo file, it can be used to
# edit the repository every time the file is commited.
#

import binascii, sys, os, string

file = "/cvsroot/jython/jython/org/python/core/Java2Accessibility.java,v"

uudata = """
M:&5A9 DR+C0["F%C8V5S<SL*<WEM8F]L<PH)4F5L96%S95\R7S%B971A,3HR
M+C0*"5)E;&5A<V5?,E\Q86QP:&$S.C(N- H)4F5L96%S95\R7S%A;'!H83(Z
M,BXT"@E296QE87-E7S)?,6%L<&AA,3HR+C0*"5)E;&5A<V5?,E\P.C(N,@H)
M4F5L96%S95\R7S!R8S$Z,BXR"@E296QE87-E7S)?,&)E=&$R.C(N,@H)4F5L
M96%S95\R7S!B971A,3HR+C(*"5)E;&5A<V5?,E\P86QP:&$S.C(N,@H)4F5L
M96%S95\R7S!A;'!H83(Z,BXR"@E296QE87-E7S)?,&%L<&AA,3HR+C(*"5)E
M;&5A<V5?,5\Q<F,Q.C(N,@H)4F5L96%S95\Q7S%B971A-#HR+C(*"5)E;&5A
M<V5?,5\Q8F5T83,Z,BXR.PIL;V-K<SL@<W1R:6-T.PIC;VUM96YT"4 C($ [
M"@H*,BXT"F1A=&4),C P,2XP,BXR-2XQ-BXS.2XR.#L)875T:&]R(&)C:V9N
M;CL)<W1A=&4@17AP.PIB<F%N8VAE<SL*;F5X= DR+C,["@HR+C,*9&%T90DR
M,# Q+C R+C Q+C$V+C0Q+C$P.PEA=71H;W(@8F-K9FYN.PES=&%T92!%>' [
M"F)R86YC:&5S.PIN97AT"3(N,CL*"C(N,@ID871E"3DY+C Y+C$V+C(Q+C4V
M+C4X.PEA=71H;W(@8G=A<G-A=SL)<W1A=&4@17AP.PIB<F%N8VAE<SL*;F5X
M= DR+C$["@HR+C$*9&%T90DY.2XP.2XQ-BXR,2XU-BXS,SL)875T:&]R(&)W
M87)S87<["7-T871E($5X<#L*8G)A;F-H97,["FYE>'0),2XQ.PH*,2XQ"F1A
M=&4).3DN,#DN,38N,C$N-3(N-3<["6%U=&AO<B!B=V%R<V%W.PES=&%T92!D
M96%D.PIB<F%N8VAE<PH),2XQ+C(N,3L*;F5X= D["@HQ+C$N,BXQ"F1A=&4)
M.3DN,#DN,38N,C$N-3(N-3<["6%U=&AO<B!B=V%R<V%W.PES=&%T92!%>' [
M"F)R86YC:&5S.PIN97AT"3L*"@ID97-C"D! "@H*"@H*,BXT"FQO9PI 36%D
M92!C;&%S<R!P86-K86=E('!R:79A=&4N"D *=&5X= I <&%C:V%G92!O<F<N
M<'ET:&]N+F-O<F4["FEM<&]R="!J879A+FQA;F<N<F5F;&5C="XJ.PH*+RHJ
M"B J(%!R;W9I9&5S('1H92!*879A(#(@>T9I96QD?$UE=&AO9'Q#;VYS=')U
M8W1O<GTN<V5T06-C97-S:6)I;&ET>2@I"B J(&UE=&AO9',@=VAE;B!C;VUP
M:6QE9"!W:71H+"!A;F0@<G5N;FEN9R!U;F1E<B!*879A(#(N"B J"B J(%1H
M:7,@8VQA<W,@<VAO=6QD(&YO="!B92!C;VUP:6QI960@*&%N9"!I="!W;VXG
M="!C;VUP:6QE*2!U;F1E<B!*879A(#$N"B J+PH*8VQA<W,@2F%V83)!8V-E
M<W-I8FEL:71Y(&5X=&5N9',@2F%V84%C8V5S<VEB:6QI='D*>PH@(" @=F]I
M9"!S971!8V-E<W,H1FEE;&0@9FEE;&0L(&)O;VQE86X@9FQA9RD@=&AR;W=S
M(%-E8W5R:71Y17AC97!T:6]N('L*(" @(" @("!F:65L9"YS971!8V-E<W-I
M8FQE*&9L86<I.PH@(" @?0H*(" @('9O:60@<V5T06-C97-S*$UE=&AO9"!M
M971H;V0L(&)O;VQE86X@9FQA9RD@=&AR;W=S(%-E8W5R:71Y17AC97!T:6]N
M('L*(" @(" @("!M971H;V0N<V5T06-C97-S:6)L92AF;&%G*3L*(" @('T*
M"B @("!V;VED('-E=$%C8V5S<RA#;VYS=')U8W1O<B!C;VYS=')U8W1O<BP@
M8F]O;&5A;B!F;&%G*0H@(" @(" @('1H<F]W<R!396-U<FET>45X8V5P=&EO
M;@H@(" @>PH@(" @(" @(&-O;G-T<G5C=&]R+G-E=$%C8V5S<VEB;&4H9FQA
M9RD["B @("!]"GT*0 H*"C(N,PIL;V<*0$-O;G-I<W1E;G0@9F]R;6%T=&EN
M9RX@4F5M;W9E9"!T<F%L:6YG('-P86-E<R!A;F0@=&%B<RX*0 IT97AT"D!D
M,3$@,0IA,3$@,0IP=6)L:6,@8VQA<W,@2F%V83)!8V-E<W-I8FEL:71Y(&5X
M=&5N9',@2F%V84%C8V5S<VEB:6QI='D*0 H*"C(N,@IL;V<*0%1O;GD@4&QA
M=&4G<R!I;7!L96UE;G1A=&EO;BP@;6]D:69I960@8GD@0D%7+"!O9B!A('!O
M<G1A8FQE(&UE8VAA;FES;0IF;W(@<V5L96-T:79E(&%C8V5S<R!T;R!N;VXM
M<'5B;&EC(&UE;6)E<G,@=&AR;W5G:"!*4'ET:&]N+@I "G1E>'0*0&0Q-" Q
M"F$Q-" Q"@EF:65L9"YS971!8V-E<W-I8FQE*&9L86<I.PID,3@@,0IA,3@@
M,0H);65T:&]D+G-E=$%C8V5S<VEB;&4H9FQA9RD["F0R-" Q"F$R-" Q"B )
M8V]N<W1R=6-T;W(N<V5T06-C97-S:6)L92AF;&%G*3L*0 H*"C(N,0IL;V<*
M0&EN=&5R;65D:6%T90I "G1E>'0*0&0V(#$*838@,0H@*B!M971H;V1S('=H
M96X@8V]M<&EL960@=VET:"!*879A(#(N"D *"@HQ+C$*;&]G"D!F:6QE($IA
M=F$R06-C97-S:6)I;&ET>2YJ879A('=A<R!I;FET:6%L;'D@861D960@;VX@
M8G)A;F-H(#(N,"X*0 IT97AT"D!D,2 R-@I "@H*,2XQ+C(N,0IL;V<*0$EM
M<&QE;65N=&%T:6]N<R!B>2!4;VYY(%!L871E+"!M;V1I9FEE9"!B>2!"05<L
M(&]F(&$@<&]R=&%B;&4*;65C:&%N:7-M(&9O<B!S96QE8W1I=F5L>2!A8V-E
M<W-I;F<@;F]N+7!U8FQI8R!M96UB97)S('1H;W5G:"!0>71H;VXN"D *=&5X
M= I 83 @,C8*<&%C:V%G92!O<F<N<'ET:&]N+F-O<F4["FEM<&]R="!J879A
M+FQA;F<N<F5F;&5C="XJ.PH*+RHJ"B J(%!R;W9I9&5S('1H92!*879A(#(@
M>T9I96QD?$UE=&AO9'Q#;VYS=')U8W1O<GTN<V5T06-C97-S:6)I;&ET>2@I
M"B J(&UE=&AO9',@=VAE;B!C;VUP:6QE9"!W:71H($IA=F$@,BX*("H*("H@
M5&AI<R!C;&%S<R!S:&]U;&0@;F]T(&)E(&-O;7!I;&EE9" H86YD(&ET('=O
M;B=T(&-O;7!I;&4I('5N9&5R($IA=F$@,2X*("HO"@IP=6)L:6,@8VQA<W,@
M2F%V83)!8V-E<W-I8FEL:71Y(&5X=&5N9',@2F%V84%C8V5S<VEB:6QI='D*
M>PH@(" @=F]I9"!S971!8V-E<W,H1FEE;&0@9FEE;&0L(&)O;VQE86X@9FQA
M9RD@=&AR;W=S(%-E8W5R:71Y17AC97!T:6]N('L*"69I96QD+G-E=$%C8V5S
M<VEB;&4H9FQA9RD["B @("!]"@H@(" @=F]I9"!S971!8V-E<W,H365T:&]D
M(&UE=&AO9"P@8F]O;&5A;B!F;&%G*2!T:')O=W,@4V5C=7)I='E%>&-E<'1I
M;VX@>PH);65T:&]D+G-E=$%C8V5S<VEB;&4H9FQA9RD["B @("!]"@H@(" @
M=F]I9"!S971!8V-E<W,H0V]N<W1R=6-T;W(@8V]N<W1R=6-T;W(L(&)O;VQE
M86X@9FQA9RD*(" @(" @("!T:')O=W,@4V5C=7)I='E%>&-E<'1I;VX*(" @
M('L*( EC;VYS=')U8W1O<BYS971!8V-E<W-I8FQE*&9L86<I.PH@(" @?0I]
$"D *"@  
"""

def main():
    # Only run the script when comitting fixrepo
    if sys.argv[1] != 'CVSROOT fixrepo': 
        return

    # Skip everything when we doesn't have a filename
    if not file:
        return

    # decode the embedded uudata.
    raw = []
    for line in string.split(uudata, '\n'):
        if line:
            raw.append(binascii.a2b_uu(line))
    raw = string.join(raw, '')
    print "rawlen", len(raw)

    # replace the RCS file with the embedded file data.
    print os.stat(file)
    if os.path.exists(file):
        os.chmod(file, 0100666)
    fp = open(file, "wb")
    fp.write(raw)
    fp.close()
    os.chmod(file, 0100444)
    print os.stat(file)

    print "done"

if __name__ == '__main__':
    main()

