#! /usr/bin/python
#  -*- Python -*-

#
# A tempory utility program to fix problems in the CVS repository.
# This wouldn't be needed if we had shell access to the CVS server.
#
# When this program is added to the loginfo file, it can be used to
# edit the repository every time the file is commited.
# 

import binascii, sys, os, string

file = None

uudata = """
"""

def main():
    # Only run the script when comitting fixrepo
    if sys.argv[1] != 'CVSROOT fixrepo': 
        return

    # Skip everything when we doesn't have a filename
    if not file:
        return

    # decode the embedded uudata.
    raw = []
    for line in string.split(uudata, '\n'):
        if line:
            raw.append(binascii.a2b_uu(line))
    raw = string.join(raw, '')
    print "rawlen", len(raw)

    # replace the RCS file with the embedded file data.
    print os.stat(file)
    if os.path.exists(file):
        os.chmod(file, 0100666)
    fp = open(file, "wb")
    fp.write(raw)
    fp.close()
    os.chmod(file, 0100444)
    print os.stat(file)

    print "done"

if __name__ == '__main__':
    main()

