package org.python.compiler.instructions;

import org.thobe.compiler.sea.ValueOperation;

public enum Invocation implements ValueOperation {
    CALL_DIRECT,
    //
    LAOD, LOAD_ATTRIBUTE, LOAD_ITEM,
    //
    INVOKE_METHOD, CALL_FUNCTION,
    //
    INVOKE_WITH_KEYWORD, CALL_WITH_KEYWORD,
    //
    INVOKE_WITH_VARARGS, CALL_WITH_VARARGS,
    //
    INVOKE_WITH_VARKEYS, CALL_WITH_VARKEYS,
    //
    INVOKE_WITH_VARARGS_AND_KEYWORD, CALL_WITH_VARARGS_AND_KEYWORD,
    //
    INVOKE_WITH_VARARGS_AND_VARKEYS, CALL_WITH_VARARGS_AND_VARKEYS,
    //
    INVOKE_WITH_KEYWORD_AND_VARKEYS, CALL_WITH_KEYWORD_AND_VARKEYS,
    //
    INVOKE_WITH_VARARG_KEYWORD_VARKEYS, CALL_WITH_VARARG_KEYWORD_VARKEYS,
}
